https://medical-records-rest-api.herokuapp.com/api/

### Crear registro
POST https://medical-records-rest-api.herokuapp.com/api/companies
content-type: application/json

{
    "name": "Test Veterinaria",
    "address": "Calle falsa 123",
    "mobile": "123456789",
    "city": "Madrid",
    "state": "Madrid",
    "observations": "Esta es una cuenta de tests",
    "statusId": 1
}

### Actualizar registro
PUT https://medical-records-rest-api.herokuapp.com/api/companies/4
content-type: application/json

{
    "name": "Test Veterinaria",
    "address": "Calle falsa 123",
    "mobile": "123456789",
    "city": "Madrid",
    "state": "Madrid",
    "observations": "Esta es una cuenta de tests",
    "statusId": 4
}

### Lista los saldos
GET http://localhost:3000/api/companies
