### Crear registro
POST http://localhost:3000/api/companies
content-type: application/json

{
    "name": "Veterinaria ACME",
    "address": "Calle falsa 123",
    "mobile": "123456789",
    "city": "Madrid",
    "state": "Madrid",
    "observations": "Esta es una cuenta de prueba",
    "statusId": 1
}

### Actualizar registro
PUT http://localhost:3000/api/companies/2
content-type: application/json

{
    "name": "Veterinaria ACME",
    "address": "Calle falsa 123",
    "mobile": "123456789",
    "city": "Madrid",
    "state": "España",
    "observations": "Esta es una cuenta de prueba",
    "statusId": 1
}

### Lista los saldos
GET http://localhost:3000/api/companies
