https://medical-records-rest-api.herokuapp.com/api/
### Crear registro
POST https://medical-records-rest-api.herokuapp.com/api/status
content-type: application/json

{
    "name": "Inactive"
}

### Listar status
GET https://medical-records-rest-api.herokuapp.com/api/status
