### Crear registro
POST https://medical-records-rest-api.herokuapp.com/api/users
content-type: application/json

{
  "id": 1,
  "email": "omar.melendrez@gmail.com",
  "name": "Omar",
  "companyId": 1,
  "profileId": 2,
  "password": "Master1*"
}

### Lista los usuarios
GET http://localhost:3000/users

### Login
POST http://localhost:3000/users/login
content-type: application/json

{
  "email": "omar.melendrez@gmail.com",
  "password": "Master1*"
}

### Update
PUT http://localhost:3000/users/1
content-type: application/json

{
  "email": "omar.melendrez@gmail.com",
  "name": "Omar Melendrez",
  "password": "Master1*",
  "companyId": 1,
  "profileId": 2
}
