### Lista clientes
GET http://localhost:3000/api/customers/inactive?filter=&page=&limit=500

### Agregar registro
POST http://localhost:3000/api/customers
content-type: application/json

{
  "name": "Omar8",
  "phone": "543210987"
}

### Borrar registro
DELETE http://localhost:3000/api/customers/6

### Recuperar registro
PUT http://localhost:3000/api/customers/1
